version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "k1-topic:1:1"
      KAFKA_CREATE_TOPICS: "k2-topic:1:1"

  
  cassandradb:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"

  m1application:
    ports:
      - "8880:8880"
    build:
      context: M1
      args:
        JAR_FILE: /M1/target/M1Application.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  
  m2application:
    ports:
      - "8881:8881"
    build:
      context: M2
      args:
        JAR_FILE: /M2/target/M2Application.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  m3application:
    ports:
      - "8882:8882"
    build:
      context: M3
      args:
        JAR_FILE: /M3/target/M3Application.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
      - cassandra
  
  m4application:
    ports:
      - "8883:8883"
    build:
      context: M4
      args:
        JAR_FILE: /M4/target/MApplication.jar
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
      - cassandra