apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: m1application
  name: m1application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: m1application
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: m1application
    spec:
      containers:
        - env:
            - name: SPRING_KAFKA_BOOTSTRAPSERVERS
              value: kafka-service:9092
          image: dedsec995/microservices-with-spring-boot_m1application
          name: m1application-container
          ports:
            - containerPort: 8880
          resources: {}
      restartPolicy: Always
status: {}
