apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: m4application
  name: m4application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: m4application
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: m4application
    spec:
      containers:
        - image: dedsec995/microservices-with-spring-boot_m4application
          name: m4application-container
          ports:
            - containerPort: 8883
          resources: {}
      restartPolicy: Always
status: {}
