apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webapplication
  name: webapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webapplication
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: webapplication
    spec:
      containers:
        - image: dedsec995/webapplication
          name: webapplication
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
